-- Migration: create nonces table
-- Description: Temporary nonces for wallet signature authentication (API-01).
--              Used in the auth flow: client requests nonce -> signs message -> API verifies.
--              Nonces expire after 5 minutes and are cleared after successful auth (API-02).
--
-- Related: API-01 (nonce endpoint), API-02 (signature verification)
-- Cleanup: Expired nonces should be deleted periodically (e.g. cron job)

-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table if not exists public.nonces (
  id               uuid        primary key default gen_random_uuid(),
  wallet_address   text        not null,
  nonce            text        unique not null,
  expires_at       timestamptz not null,
  created_at       timestamptz not null default now(),
  used_at          timestamptz
);

-- =============================================================================
-- 2. CONSTRAINTS
-- =============================================================================
-- wallet_address: Stellar Ed25519 public key format (G + 55 base32 chars)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'nonces_wallet_address_format_check'
  ) then
    alter table public.nonces
      add constraint nonces_wallet_address_format_check
      check (wallet_address ~ '^G[A-Z2-7]{55}$');
  end if;
end;
$$;

-- expires_at must be in the future at insert time
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'nonces_expires_at_check'
  ) then
    alter table public.nonces
      add constraint nonces_expires_at_check
      check (expires_at > created_at);
  end if;
end;
$$;

-- =============================================================================
-- 3. INDEXES
-- =============================================================================
create index if not exists idx_nonces_wallet_address on public.nonces (wallet_address);
create index if not exists idx_nonces_nonce on public.nonces (nonce);
create index if not exists idx_nonces_expires_at on public.nonces (expires_at);

-- =============================================================================
-- 4. COMMENTS
-- =============================================================================
comment on table public.nonces is
  'Temporary nonces for wallet signature authentication. '
  'Generated by POST /auth/nonce, consumed by POST /auth/verify (API-02). '
  'Expire after 5 minutes. used_at set when nonce is consumed.';

comment on column public.nonces.wallet_address is
  'Stellar Ed25519 public key (G + 55 base32 chars).';

comment on column public.nonces.nonce is
  'Cryptographically secure random hex string (64 chars).';

comment on column public.nonces.expires_at is
  'Nonce expiration timestamp. Client must complete auth before this time.';

comment on column public.nonces.used_at is
  'Set when nonce is consumed by successful signature verification.';
